name: NuclearCraft
version: '${project.version}'
main: com.enderryno.nuclearcraft.NuclearCraft
api-version: 1.18
authors: [ Rynoooo, Corvinoo ]
description: A plugin that adds nuclear energy, along with his advantages and dangers
website: http://rynotechblog.altervista.org/
commands:
  give:
    description: Give a nuclear craft item
    permission: nuclearcraft.admin
    permission-message: You do not have permission!
    usage: /<command> [id]